version: '3'
services:
  mongodb:
    image: mongo
    volumes:
     - ./mongo/data:/data/db
  httpd:
    image: httpd
    ports:
     - "8443:8443"
    volumes:
     - ./src/main/resources/:/usr/local/apache2/htdocs/
     - ./httpd/server-static.conf:/usr/local/apache2/conf/httpd.conf
     - ./httpd/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
     - ./httpd/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
    depends_on:
     - server
  microauth:
    build:
      context: ./microauth
    volumes:
      - ./microauth/authorizationServer.js:/server/authorizationServer.js
    ports:
      - "9001:9001"
    command: node ./authorizationServer.js
  server:
    build:
      context: ./server-dev
    ports:
     - "9999:9999"
    volumes:
     - ./target/:/server/
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/fapi-test-suite.jar
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
    links:
     - mongodb:mongodb
     - microauth:microauth
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
